import { Familjen_Grotesk, Krona_One } from "next/font/google";
import "./globals.css";

const openSans = Familjen_Grotesk({ subsets: ["latin"] });
const kronaOne = Krona_One({subsets: ["latin"], weight: ["400"]});

export const metadata = {
  title: "IMEX2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kronaOne.className}>
        {children}
      </body>
    </html>
  );
}
