
import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";

const openSans = Familjen_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "IMEX2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        {children}
      </body>
    </html>
  );
}
